version: "2.4"
services:
  zookeeper1:
    image: digitalwonderland/zookeeper
    container_name: zookeeper1
    environment:
      - ZOOKEEPER_ID=1
      - ZOOKEEPER_SERVER_1=zookeeper1
#      - ZOOKEEPER_SERVER_2=zookeeper2
#      - ZOOKEEPER_SERVER_3=zookeeper3
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888


  zookeeper2:
    image: digitalwonderland/zookeeper
    container_name: zookeeper2
    environment:
      - ZOOKEEPER_ID=2
#      - ZOOKEEPER_SERVER_1=zookeeper1
      - ZOOKEEPER_SERVER_2=zookeeper2
#      - ZOOKEEPER_SERVER_3=zookeeper3
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - 2182:2181
      - 2889:2888
      - 3889:3888


  zookeeper3:
    image: digitalwonderland/zookeeper
    container_name: zookeeper3
    environment:
      - ZOOKEEPER_ID=3
      - ZOOKEEPER_SERVER_1=zookeeper1
      - ZOOKEEPER_SERVER_2=zookeeper2
      - ZOOKEEPER_SERVER_3=zookeeper3
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - 2183:2181
      - 2890:2888
      - 3890:3888


  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    environment:
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ADVERTISED_HOST_NAME=localhost
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181
      - KAFKA_LOG_RETENTION_HOURS=4
      - KAFKA_LOG_RETENTION_BYTES=1000000000
    ports:
      - 9092:9092

  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    environment:
#      - KAFKA_ADVERTISED_PORT=9093
#      - KAFKA_ADVERTISED_HOST_NAME=localhost
##      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
#      - KAFKA_BROKER_ID=10002
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181
#      - KAFKA_LOG_RETENTION_HOURS=4
#      - KAFKA_LOG_RETENTION_BYTES=1000000000
#      - KAFKA_LISTENERS= PLAINTEXT://kafka2:9093
#      - KAFKA_ADVERTISED_LISTENERS= PLAINTEXT://kafka2:9093
        # For more details see See https://rmoff.net/2018/08/02/kafka-listeners-explained/
      - KAFKA_LISTENERS: LISTENER_FRED://kafka0:9092
      - KAFKA_ADVERTISED_LISTENERS: LISTENER_FRED://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_FRED:PLAINTEXT
#      - KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
    ports:
      - '9092:9092'
      - '29094:29094'

  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3
    environment:
      - KAFKA_ADVERTISED_PORT=9094
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_LOG_RETENTION_HOURS=4
      - KAFKA_LOG_RETENTION_BYTES=1000000000
    ports:
      - 9094:9092