---
version: '2.4'
services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:5.2.1"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # This has three listeners you can experiment with.
  # BOB for internal traffic on the Docker network
  # FRED for traffic from the Docker-host machine (`localhost`)
  # ALICE for traffic from outside, reaching the Docker host on the DNS name `never-gonna-give-you-up`
  # Use
  kafka0:
    image: "confluentinc/cp-enterprise-kafka:5.2.1"
    ports:
      - '9092:9092'
      - '29092:29092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID= 0
      - KAFKA_ZOOKEEPER_CONNECT= zookeeper:2181
      - KAFKA_LISTENERS= LISTENER_BOB://kafka0:9092,LISTENER_FRED://kafka0:29092,LISTENER_ALICE://kafka0:29094
      - KAFKA_ADVERTISED_LISTENERS= LISTENER_BOB://kafka0:9092,LISTENER_FRED://localhost:29092,LISTENER_ALICE://never-gonna-give-you-up:29094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP= LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT,LISTENER_ALICE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME= LISTENER_BOB
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE= TRUE
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR= 1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS= 100

  kafkacat:
    image: confluentinc/cp-kafkacat
    command: sleep infinity